# fly.toml file generated for muddy-moon-8512 on 2023-02-15T16:30:44Z

app = "muddy-moon-8512"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ENV = "production"

[experimental]
  auto_rollback = true
