name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  fly:
    name: Dependabot
    uses: LeoColomb/.github/.github/workflows/deploy.yml@main
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
