name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.3
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - id: tailscale
        env:
          TS_API_CLIENT_ID: ${{ secrets.TS_API_CLIENT_ID }}
          TS_API_CLIENT_SECRET: ${{ secrets.TS_API_CLIENT_SECRET }}
        run: |
          auth_key=$(go run tailscale.com/cmd/get-authkey@main -ephemeral -tags tag:local)
          echo "::add-mask::$auth_key"
          echo "auth-key=$auth_key" >> "$GITHUB_OUTPUT"
      - run: flyctl secrets set --stage TAILSCALE_AUTHKEY=${{ steps.tailscale.outputs.auth-key }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
