name: CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          cache: pipenv

      - name: Install pipenv
        run: pip install --user pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Lint
        run: pipenv run lint --output-format=github
