name: Fly Sync

on:
  workflow_dispatch:

jobs:
  secrets:
    strategy:
      matrix:
        include:
          - name: GRDF_CLIENT_ID
            id: "f0501f42-b8b4-444d-ba2d-0d57a75971f9"
          - name: GRDF_CLIENT_SECRET
            id: "4277bc00-b687-49c4-bf7c-954c6e209c2f"
          - name: PCE
            id: "13ace5e4-ef3a-4af8-a0df-efe5c708e67b"
          - name: PDL
            id: "633bf770-c8b4-43cb-b43a-e9c56515707e"
    name: Secrets
    uses: LeoColomb/.github/.github/workflows/secrets-sync.yml@main
    with:
      name: ${{ matrix.name }}
      id: ${{ matrix.id }}
    secrets: inherit
