name: Fly Sync

on:
  workflow_dispatch:

jobs:
  secrets:
    strategy:
      matrix:
        include:
          - name: GRDF_CLIENT_ID
            id: "1e2401a2-1adf-4d3f-a9d1-b17800859a47"
          - name: GRDF_CLIENT_SECRET
            id: "d50618d9-220e-4754-b0bf-b178008630b5"
          - name: PCE
            id: "08342bd1-3ce2-4102-b202-b17800865ef4"
          - name: PDL
            id: "d9214c8d-9c40-45e4-9a36-b17800867d98"
    name: Secrets
    uses: LeoColomb/.github/.github/workflows/secrets-sync.yml@main
    with:
      name: ${{ matrix.name }}
      id: ${{ matrix.id }}
    secrets: inherit
